server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db:3306/db_memberboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: memberboard
    password: 1234

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    layout-dialect: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate.hbm2ddl.auto: update

openai:
  api-key: "OPENAI_API_KEY"